version: '3'
services:
  test:
    image: zonawik1/save_uplink_to_neo4jdb:1
    command: >
      bash -c " service neo4j start &&
      sleep 5 &&
      echo "CALL dbms.changePassword('neo4j-password');" | cypher-shell -u neo4j -p neo4j --format verbose &&
      echo "CREATE (:Thing {name: '2BEE82'});" | cypher-shell -u neo4j -p neo4j-password --format verbose &&
      bundle && rspec &&
      chmod +x bin/shot &&
      bin/shot"
    volumes:
      - .:/lambda_docker
    tty: true
    stdin_open: true

  update:
     image: zonawik1/save_uplink_to_neo4jdb:1
     command: >
       bash -c "apt-get install -y zip &&
       bundle install --path vendor/bundle --without development test &&
       rm -r vendor/bundle/ruby/2.5.0/cache &&
       zip -9 -r lambda_function.zip lambda_function.rb vendor app config lib &&
       aws lambda update-function-code --function-name  arn:aws:lambda:us-east-1:247246293844:function:SaveToNeo4jDB --zip-file fileb://lambda_function.zip"
     volumes:
       - .:/lambda_docker
     tty: true
     stdin_open: true
